# Generated by Django 6.0.7 on 2026-09-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_product_is_featured_product_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='button_link',
            field=models.CharField(default='#', help_text='প্রোডাক্ট সিলেক্ট করা থাকলে কাস্টম লিংক লাগবে না', max_length=255),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.CharField(blank=True, default='Terms and Conditions Apply', max_length=255),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='product',
            field=models.ForeignKey(blank=True, help_text='প্রোডাক্ট সিলেক্ট করলে সেটির তথ্য অটো নিয়ে নিবে (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousels', to='MyApp.product'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Subtitle (e.g. Save Up To ৳400)', max_length=255),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, help_text='প্রোডাক্ট সিলেক্ট করলে খালি রাখুন, অটো চলে আসবে', max_length=255),
        ),
    ]
