# Generated by Django 6.0.7 on 2026-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram Link'),
        ),
    ]
