# Generated by Django 6.0.7 on 2026-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sender_bkash_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
